name: CI
permissions:
  contents: read
on:
  push:
jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: vmactions/openbsd-vm@v1
        with:
          prepare: |
            pkg_add sqlite3
          run: make test
