name: CI
permissions:
  contents: read
on:
  push:
jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: openbsd
          version: '7.8'
          run: |
            sudo pkg_add sqlite3
            make test
